name: Test Docker Image from Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (if you need to use local test files or code)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Pull the Docker image from Docker Hub
      - name: Pull Docker image from Docker Hub
        run: |
          docker pull valjean68/pipeline:reconn

      # Run tests inside the Docker container
      - name: Run tests in Docker container
        run: |
          docker run -d --name my_container valjean68/pipeline:reconn
      # Mira mira mira sacale una foto
      - name: Mira mira mira sacale una foto
        run: echo "Grande DevOps"

      - name: Stop and remove Docker container
        run: |
          docker stop my_container
          docker rm my_container
